// SQUID
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const LATLNG_TO_LATLNG_INIT = 'LATLNG_TO_LATLNG_INIT';
export const LATLNG_TO_LATLNG_SUCCESS = 'LATLNG_TO_LATLNG_SUCCESS';
export const LATLNG_TO_LATLNG_FAILURE = 'LATLNG_TO_LATLNG_FAILURE';
