// SQUID
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const LATLONG_TO_LATLONG_INIT = 'LATLONG_TO_LATLONG_INIT';
export const LATLONG_TO_LATLONG_SUCCESS = 'LATLONG_TO_LATLONG_SUCCESS';
export const LATLONG_TO_LATLONG_FAILURE = 'LATLONG_TO_LATLONG_FAILURE';
